### ISSUE TITLE
Linking contact to company

### ISSUE THREAD

**Issue by sheam** [skarpdev/dotnetcore-hubspot-client#69]
Excited to find this project.

I need to create a Contact, Company, and Deal.

First I create a contact. _Now when I am creating the Company, how do I link the contact to that company?_

Is there an ETA for the Deal client?

**Comment by roycornelissen** [comment]
Hi, we're doing the same thing as you: creating Contacts, Companies and Deals using this API. In general, you can link almost everything to everything using the `AssociationsClient`. You just create an AssociationHubSpotEntity with the proper type (`HubSpotAssociationDefinitions.ContactToCompany` in this case).

But you can also do it in one go... We first create (or resolve by domain) the `Company`. You will then have the ID of the `Company`. We have a custom definition for our `Contact` entity (because we also add another custom field), like this:

```csharp
[DataContract]
public class MyCustomContactHubSpotEntity: ContactHubSpotEntity
{
    [DataMember(Name = "our_custom_property")]
    public string CustomProperty { get; set; }

    [DataMember(Name = "hubspot_owner_id")]
    public string OwnerId { get; set; }
    [DataMember(Name = "associatedcompanyid")]
    public string AssociatedCompanyId { get; set; }
}
```

The two fields `hubspot_owner_id` and `associatedcompanyid` are existing HubSpot fields, but they're not exposed in the base `ContactHubSpotEntity`. By adding them here, you can assign the new contact to the `Company` and also directly to an `Owner` while creating it. You can also retrieve them from HubSpot if you request these properties as additional properties.

When creating a `Deal`, we do use the `AssociationsClient`, it looks like this:

```csharp
// create the deal
var deal = new DealHubSpotEntity
{
    Name = $"{productName} for {company.Name}",
    Pipeline = settings.DealPipeline, // you can find these in the HubSpot settings in the definition of the pipeline
    Stage = settings.NewDealStage, // you can find these in the HubSpot settings in the definition of the pipeline
    DealType = settings.NewDealType,
    OwnerId = hubSpotOwnerId,
    Amount = // some total amount that you calculate
};
// You can associate the deal to the company like this
deal.Associations.AssociatedCompany = new[] { companyId };

deal = await dealClient.CreateAsync<DealHubSpotEntity>(deal).ConfigureAwait(false);

// Associate line items with deal
var dealAssociations = new List<AssociationHubSpotEntity>();
foreach (var lineItem in createdLineItems) // assuming createdLineItems have been created before
{
    dealAssociations.Add(new AssociationHubSpotEntity
    {
        FromObjectId = deal.Id!.Value,
        ToObjectId = lineItem.Id!.Value,
        DefinitionId = (int)Skarp.HubSpotClient.Core.HubSpotAssociationDefinitions.DealToLineItem
    });
}

// associate the deal to the contact
dealAssociations.Add(new AssociationHubSpotEntity
{
    FromObjectId = deal.Id!.Value,
    ToObjectId = hubSpotContactId,
    DefinitionId = (int)Skarp.HubSpotClient.Core.HubSpotAssociationDefinitions.DealToContact
});

await associationClient.CreateBatch(dealAssociations).ConfigureAwait(false);
```

So the `HubSpotDealClient` is in fact already available :)

**Comment by sheam** [comment]
This should work for me, thank you.
